### ISSUE TITLE
Opening the app will launch the web browser

### ISSUE THREAD

**Issue by cm-t** [uiiverse/UBports#1]
excpected result:
* open app will allow to browse the app in it's windows

issue:
* open app will open its window and instantly then launch the browser

* Edit: i had another tab opebed in my browser, didnt see at first: an Ads was there. probably the ads launched the browser. 

hint: if it's a webapp, there must be something with the settings. you might want to deny opening link outsode the webapp. there is also a setting to allow outside link to open as a pop-in.

v. 1.0 on: 
Meizu Pro 5 international on candidate build 2020-W16

**Comment by wiredsis** [comment]
Ok. Fixed the issue.
